spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ggoogle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ggoogle
    password: 1234

  jpa:
    properties:
      hibernate:
        ddl_auto: create
        show_sql: true
        format_sql: true
    generate-ddl: true
    show-sql: true
    database: mysql
    defer-datasource-initialization: true

  #  sql:
  #    init:
  #      mode: always